### ISSUE TITLE
ValueError: Can't normalize Vector of length Zero

### ISSUE THREAD

**Issue by aaron-jencks** [PrathameshBhatkar/Boids_Simulation#1]
```
Traceback (most recent call last):
  File "/home/aaron/.../github/Boids_Simulation/./Boids.py", line 231, in <module>
    b.simulate_boid_rules()
  File "/home/aaron/.../github/Boids_Simulation/./Boids.py", line 83, in simulate_boid_rules
    dir = dir.normalize() / repel
ValueError: Can't normalize Vector of length Zero
```

I enabled simulation, then turned on all 3 of the provided rules, with the default values, waited a few seconds, and it crashed

**Comment by aaron-jencks** [comment]
You can fix this by skipping when 2 boids are on top of each other
I'll make a PR for this
